

define [], () ->

  class ConstantService
    constructor: (@$rootScope, @$http) ->
      if localStorage.getItem 'preference'
        preference = JSON.parse localStorage.getItem 'preference'
        ip = preference?.ip
      @ip = ip ? "127.0.0.1"
      @init()
      @setWindowSetting()

    changeIp: (ip) ->
      @ip = ip
      @init()
      @setWindowSetting()

    init: ->
      @TOAST_SHORT_DELAY = 2000
      @TOAST_LONG_DELAY = 3500

      @loginCookie = 'clc-login-info'
      @tokenCookie = 'clc-token-info'

      @storeName = 'clc-mobile'

      @urls =
        login: 'http://'+@ip+'/auth/login'
        register: 'http://'+@ip+'/auth/register'

      @ioUrl = 'http://'+@ip

    setWindowSetting: ->
      window.setting =
#        'entranceUrl': 'http://127.0.0.1/model/clc/api/v1/keyvalues/admin/iiot-cloud/entrance?token=fee68160-4dec-11e8-b3f2-bbf228d2b4f7'
#        'entranceUrl': 'http://127.0.0.1/model/clc/api/v1/keyvalues/admin/micromodule/entrance?token=a07a0440-7f37-11e8-bf07-611c7b579964'
        'entranceUrl': 'http://cloud.huayuan-iot.com/model/clc/api/v1/keyvalues/admin/info/entrance?token=98655510-f850-11e8-9681-c905a56f3896'
        'services':
          'api': 'clc/api/v1'
          'gateway': '/gateway'
          'auth': '/auth'
          'model': '/model'
          'bus': '/bus'
          'resource': '/resource'
          'visualization': '/visualization'
          'reporting': '/reporting'
          'notification': '/notification'
          'video': '/video'
          'monitoring': '/monitoring'
          'store': '/cloud'
          'portal': '/portal'
          'doc': '/doc'
          'dcim': '/dcim'
          'cloudview': '/cloudview'
          'cmms': '/cmms'
          'connection': '/connection'
          'smartrack': '/smartrack'
        'urls':
          'login': 'http://'+@ip+'/auth/#/login'
          'logout': 'http://'+@ip+'/auth/#/logout'
          'authenticate': 'http://'+@ip+'/auth/authenticate'
          'changePassword': 'http://'+@ip+'/auth/#/changepassword'
          'forgetPassword': 'http://'+@ip+'/auth/#/forgetpassword'
          'resetPassword': 'http://'+@ip+'/auth/#/resetpassword'
          'getToken': 'http://'+@ip+'/auth/token/:username/:password'
          'validatePassword': 'http://'+@ip+'/auth/validatepassword/:username'
          'sendSmsCode': 'http://'+@ip+'/auth/sendsmscode/:phone'
          'model.login': 'http://'+@ip+'/model/clc/api/v1/system/login'
          'model.authenticate': 'http://'+@ip+'/model/clc/api/v1/system/authenticate'
          'model.logout': 'http://'+@ip+'/model/clc/api/v1/system/logout'
          'model.changePassword': 'http://'+@ip+'/model/clc/api/v1/system/changepassword'
          'model.changeToken': 'http://'+@ip+'/model/clc/api/v1/system/changeToken'
          'activateUser': 'http://'+@ip+'/model/clc/api/v1/system/activate/:user/:key'
          'uploadUrl': 'http://'+@ip+'/resource/upload/img/public'
          'fileUrl': 'http://'+@ip+'/resource/upload/file/public'
          'usersUploadUrl': 'http://'+@ip+'/resource/upload/img/users'
          'downloadUrl': 'http://'+@ip+'/resource/download/:url'
          'register': 'http://'+@ip+'/model/clc/api/v1/system/register'
          'users': 'http://'+@ip+'/model/clc/api/v1/users'
          'user': 'http://'+@ip+'/model/clc/api/v1/users/:user'
          'projects': 'http://'+@ip+'/model/clc/api/v1/projects/:user'
          'project': 'http://'+@ip+'/model/clc/api/v1/projects/:user/:project'
          'datatypes': 'http://'+@ip+'/model/clc/api/v1/datatypes/:user/:project/:type'
          'signaltypes': 'http://'+@ip+'/model/clc/api/v1/signaltypes/:user/:project/:type'
          'stationtypes': 'http://'+@ip+'/model/clc/api/v1/stationtypes/:user/:project/:type'
          'eventtypes': 'http://'+@ip+'/model/clc/api/v1/eventtypes/:user/:project/:type'
          'eventseverities': 'http://'+@ip+'/model/clc/api/v1/eventseverities/:user/:project/:severity'
          'eventphases': 'http://'+@ip+'/model/clc/api/v1/eventphases/:user/:project/:phase'
          'porttypes': 'http://'+@ip+'/model/clc/api/v1/porttypes/:user/:project/:type'
          'units': 'http://'+@ip+'/model/clc/api/v1/units/:user/:project/:unit'
          'monitoringunits': 'http://'+@ip+'/model/clc/api/v1/monitoringunits/:user/:project/:unit'
          'vendors': 'http://'+@ip+'/model/clc/api/v1/vendors/:user/:project/:vendor'
          'equipmenttypes': 'http://'+@ip+'/model/clc/api/v1/equipmenttypes/:user/:project/:type'
          'equipmenttemplates': 'http://'+@ip+'/model/clc/api/v1/equipmenttemplates/:user/:project/:type/:template'
          'equipmentsignals': 'http://'+@ip+'/model/clc/api/v1/equipmentsignals/:user/:project/:type/:template/:signal'
          'equipmentevents': 'http://'+@ip+'/model/clc/api/v1/equipmentevents/:user/:project/:type/:template/:event'
          'equipmentcommands': 'http://'+@ip+'/model/clc/api/v1/equipmentcommands/:user/:project/:type/:template/:command'
          'equipmentproperties': 'http://'+@ip+'/model/clc/api/v1/equipmentproperties/:user/:project/:type/:template/:property'
          'equipmentports': 'http://'+@ip+'/model/clc/api/v1/equipmentports/:user/:project/:type/:template/:port'
          'equipmentstates': 'http://'+@ip+'/model/clc/api/v1/equipmentstates/:user/:project/:state'
          'stationstates': 'http://'+@ip+'/model/clc/api/v1/stationstates/:user/:project/:state'
          'stations': 'http://'+@ip+'/model/clc/api/v1/stations/:user/:project/:station'
          'equipments': 'http://'+@ip+'/model/clc/api/v1/equipments/:user/:project/:station/:equipment'
          'eventnotifications': 'http://'+@ip+'/model/clc/api/v1/eventnotifications/:user/:project/:notification'
          'roles': 'http://'+@ip+'/model/clc/api/v1/roles/:user/:project/:role'
          'capacities': 'http://'+@ip+'/model/clc/api/v1/capacities/:user/:project/:capacity'
          'graphictypes': 'http://'+@ip+'/model/clc/api/v1/graphictypes/:user/:project/:type'
          'graphictemplates': 'http://'+@ip+'/model/clc/api/v1/graphictemplates/:user/:project/:template'
          'watches': 'http://'+@ip+'/model/clc/api/v1/watches/:user/:project/:watch'
          'reporttemplates': 'http://'+@ip+'/model/clc/api/v1/reporttemplates/:user/:project/:template'
          'reportfiles': 'http://'+@ip+'/model/clc/api/v1/reportfiles/:user/:project/:file'
          'reporting.signalrecords': 'http://'+@ip+'/model/clc/api/v1/reporting/signal-records/:user/:project'
          'reporting.signalgrouprecords': 'http://'+@ip+'/model/clc/api/v1/reporting/signal-group-records/:user/:project'
          'reporting.signalStatistics': 'http://'+@ip+'/model/clc/api/v1/reporting/signal-statistics/:user/:project'
          'reporting.eventrecords': 'http://'+@ip+'/model/clc/api/v1/reporting/event-records/:user/:project'
          'reporting.commandrecords': 'http://'+@ip+'/model/clc/api/v1/reporting/command-records/:user/:project'
          'reporting.operationrecords': 'http://'+@ip+'/model/clc/api/v1/reporting/operation-records'
          'reporting.records.signal': 'http://'+@ip+'/model/clc/api/v1/reporting/records/signal/:user/:project'
          'reporting.records.signal-group': 'http://'+@ip+'/model/clc/api/v1/reporting/records/signal-group/:user/:project'
          'reporting.records.signal-statistic': 'http://'+@ip+'/model/clc/api/v1/reporting/records/signal-statistic/:user/:project'
          'reporting.records.event': 'http://'+@ip+'/model/clc/api/v1/reporting/records/event/:user/:project'
          'reporting.records.command': 'http://'+@ip+'/model/clc/api/v1/reporting/records/command/:user/:project'
          'reporting.records.operation': 'http://'+@ip+'/model/clc/api/v1/reporting/records/operation'
          'reporting.aggregate.signal': 'http://'+@ip+'/model/clc/api/v1/reporting/aggregate/signal/:user/:project'
          'reporting.aggregate.signal-group': 'http://'+@ip+'/model/clc/api/v1/reporting/aggregate/signal-group/:user/:project'
          'reporting.aggregate.signal-statistic': 'http://'+@ip+'/model/clc/api/v1/reporting/aggregate/signal-statistic/:user/:project'
          'reporting.aggregate.event': 'http://'+@ip+'/model/clc/api/v1/reporting/aggregate/event/:user/:project'
          'reporting.aggregate.command': 'http://'+@ip+'/model/clc/api/v1/reporting/aggregate/command/:user/:project'
          'reporting.aggregate.operation': 'http://'+@ip+'/model/clc/api/v1/reporting/aggregate/operation'
          'reporting.aggregate.notification': 'http://'+@ip+'/model/clc/api/v1/reporting/aggregate/notification/:user/:project'
          'reporting.aggregate.task': 'http://'+@ip+'/model/clc/api/v1/reporting/aggregate/task/:user/:project'
          'star': 'http://'+@ip+'/model/clc/api/v1/star/:user/:project/:starUser'
          'token': 'http://'+@ip+'/model/clc/api/v1/token/:token'
          'role': 'http://'+@ip+'/model/clc/api/v1/role/:user/:project'
          'issues': 'http://'+@ip+'/model/clc/api/v1/issues/:user/:project/:issue'
          'sprints': 'http://'+@ip+'/model/clc/api/v1/sprints/:user/:project/:sprint'
          'processtypes':'http://'+@ip+'/model/clc/api/v1/processtypes/:user/:project/:type'
          'tasks': 'http://'+@ip+'/model/clc/api/v1/tasks/:user/:project/:type/:process/:task'
          'inventorystatistics': 'http://'+@ip+'/model/clc/api/v1/statistic/inventory/:user/:project/:station/:equipmentType/:role/:period'
          'dynamicstatistics': 'http://'+@ip+'/model/clc/api/v1/statistic/dynamic/:user/:project/:station/:equipment/:valueType/:period'
          'notifications': 'http://'+@ip+'/notification/clc/api/v1/notifications/:user/:project/:notification'
          'notificationrules': 'http://'+@ip+'/model/clc/api/v1/notificationrules/:user/:project/:notification'
          'notificationrecords': 'http://'+@ip+'/model/clc/api/v1/notificationrecords/:user/:project/:notification'
          'connectiontypes': 'http://'+@ip+'/model/clc/api/v1/connectiontypes/:user/:project/:type'
          'connections': 'http://'+@ip+'/model/clc/api/v1/connections/:user/:project/:station/:connection'
          'connect': 'http://'+@ip+'/model/clc/api/v1/connect/:user/:project/:station/:equipment'
          'calendarevents': 'http://'+@ip+'/model/clc/api/v1/calendarevents/:user/:project/:station/:event'
          'todotasks': 'http://'+@ip+'/model/clc/api/v1/todotasks/:user/:project/:station/:task'
          'apis': 'http://'+@ip+'/model/clc/api/v1/apis/:api'
          'apifeatures': 'http://'+@ip+'/model/clc/api/v1/apifeatures/:api/:feature'
          'shorts': 'http://'+@ip+'/model/clc/api/v1/shorts/:short'
          'short': 'http://'+@ip+'/model/s'
          'keyvalues': 'http://'+@ip+'/model/clc/api/v1/keyvalues/:user/:project/:key'
          'keyvalue': 'http://'+@ip+'/model/kv'
          'operationtemplates': 'http://'+@ip+'/model/clc/api/v1/operationtemplates/:user/:project/:station/:template'
          'cmms.operationtemplates': 'http://'+@ip+'/model/clc/api/v1/cmms/operationtemplates/:user/:project/:station/:template'
          'cmms.events': 'http://'+@ip+'/model/clc/api/v1/cmms/events/:user/:project/:station/:event'
          'cmms.tickets': 'http://'+@ip+'/model/clc/api/v1/cmms/tickets/:user/:project/:station/:ticket'
          'cmms.teams': 'http://'+@ip+'/model/clc/api/v1/cmms/teams/:user/:project/:station/:team'
          'cmms.schedules': 'http://'+@ip+'/model/clc/api/v1/cmms/schedules/:user/:project/:station/:schedule'
          'inventory.statisticByEquipmentTypes': 'http://'+@ip+'/model/clc/api/v1/inventory/statistic-by-equipment-types/:user/:project/:station'
          'inventory.lifetime': 'http://'+@ip+'/model/clc/api/v1/inventory/lifetime/:user/:project/:station'
          'doc.search': 'http://'+@ip+'/portal/clc/api/v1/search'
          'res.search': 'http://'+@ip+'/resource/clc/api/v1/search'
          'model.search': 'http://'+@ip+'/model/clc/api/v1/search'
          'resources': 'http://'+@ip+'/model/clc/api/v1/resources/:user/:project/:resource'
          'operations': 'http://'+@ip+'/model/clc/api/v1/operations/:user/:type/:operation'
          'updateSignals': 'http://'+@ip+'/model/clc/api/v1/updateSignals/:user/:project/:station/:equipment'
          'updateEvents': 'http://'+@ip+'/model/clc/api/v1/updateEvents/:user/:project/:station/:equipment'
          'updateCommands': 'http://'+@ip+'/model/clc/api/v1/updateCommands/:user/:project/:station/:equipment'
          'pauseChanges': 'http://'+@ip+'/model/clc/api/v1/pauseChanges/:user/:project/:period'
          'generateProject': 'http://'+@ip+'/model/clc/api/v1/generateProject/:user/:project'

  exports =
    Constants: ConstantService
