// Generated by IcedCoffeeScript 108.0.11

/*
* File: reporting-service
* User: Dow
* Date: 9/2/2015
* Desc:
 */
if (typeof define !== 'function') { var define = require('amdefine')(module) };
var __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

define(['./query-service'], function(base) {
  var ReportingService, exports;
  ReportingService = (function(_super) {
    __extends(ReportingService, _super);

    function ReportingService($rootScope, $http, urls) {
      this.urls = urls;
      ReportingService.__super__.constructor.call(this, $rootScope, $http);
    }

    ReportingService.prototype.queryRecords = function(key, data, callback) {
      var url;
      url = this.urls[key];
      if (!url) {
        return callback("" + key + " url is not defined");
      }
      return this.query(url, data, callback);
    };

    ReportingService.prototype.querySignalRecords = function(data, callback) {
      var key;
      key = 'reporting.signalrecords';
      return this.queryRecords(key, data, callback);
    };

    ReportingService.prototype.querySignalGroupRecords = function(data, callback) {
      var key;
      key = 'reporting.signalgrouprecords';
      return this.queryRecords(key, data, callback);
    };

    ReportingService.prototype.queryEventRecords = function(data, callback) {
      var key;
      key = 'reporting.eventrecords';
      return this.queryRecords(key, data, callback);
    };

    ReportingService.prototype.queryCommandRecords = function(data, callback) {
      var key;
      key = 'reporting.commandrecords';
      return this.queryRecords(key, data, callback);
    };

    return ReportingService;

  })(base.QueryService);
  return exports = {
    ReportingService: ReportingService
  };
});
