// Generated by IcedCoffeeScript 108.0.11
define([], function() {
  var exports, service;
  service = function(store, settingService) {
    return store.getNamespacedStore(settingService.storeName);
  };
  return exports = {
    service: service
  };
});
